#!/usr/bin/env bash
rm -rf dist
mkdir -p dist
echo "transpile index.ls to index.js ..."
./node_modules/.bin/lsc -cpb src/index.ls > dist/index.js
echo "minifying index.js ..."
./node_modules/.bin/uglifyjs dist/index.js -m -c > dist/index.min.js

echo "Copy dist/ to web/ ..."
rm -rf web/static/assets/lib/@plotdb/quill-image/main/
mkdir -p web/static/assets/lib/@plotdb/quill-image/main/
cp -R dist/* web/static/assets/lib/@plotdb/quill-image/main/
echo "done."

