#!/usr/bin/env bash
rm -rf dist
mkdir -p dist
echo "transpile index.ls to index.js ..."
./node_modules/.bin/lsc -cpb src/index.ls > dist/index.js
echo "minifying index.js ..."
./node_modules/.bin/uglifyjs dist/index.js -m -c > dist/index.min.js
echo "build src/index.styl -> dist/index.css ..."
./node_modules/.bin/stylus -p src/index.styl > dist/index.css
echo "minifying index.css ..."
./node_modules/.bin/uglifycss dist/index.css > dist/index.min.css

echo "Copy dist/ to web/ ..."
rm -rf web/static/assets/lib/@plotdb/quill-image-plus/main/
mkdir -p web/static/assets/lib/@plotdb/quill-image-plus/main/
cp -R dist/* web/static/assets/lib/@plotdb/quill-image-plus/main/
echo "done."

